services:
  simplephotos:
    image: lzyyauto/simplephotos:latest
    ports:
      - "5173:5173"
    volumes:
      - /path/to/your/data:/app/data
    environment:
      - NODE_ENV=production
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      - DATA_ROOT=/app/data
      - SCAN_WORKERS=4      # 线程数
      - SCAN_CHUNK_SIZE=100 # 每个线程一次处理的文件数
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'

volumes:
  data:
    driver: local