services:
  simplephotos:
    image: lzyyauto/simplephotos:latest
    ports:
      - "5173:5173"
    volumes:
      - ${PWD}/data:/app/data
    environment:
      - NODE_ENV=production
      - LANG=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      - DATA_ROOT=/app/data

volumes:
  data:
    driver: local